# Consider the following list of students. student is a list of 20 dictionaries, and each dictionary contains the
# student’s id and marks in M ath, Computer Science, and Science.
# student=[{“student id” : 1, “M ath” : 50, “Computer Science” : 60, “Science” : 73},
# {“student id” : 2, “M ath” : 40, “Computer Science” : 50, “Science” : 55},
# {“student id” : 3, “M ath” : 90, “Computer Science” : 70, “Science” : 95},
# {“student id” : 4, “M ath” : 80, “Computer Science” : 62, “Science” : 72},
# {“student id” : 5, “M ath” : 80, “Computer Science” : 90, “Science” : 45},
# {“student id” : 6, “M ath” : 84, “Computer Science” : 90, “Science” : 50},
# {“student id” : 7, “M ath” : 90, “Computer Science” : 95, “Science” : 55},
# {“student id” : 8, “M ath” : 89, “Computer Science” : 93, “Science” : 53},
# {“student id” : 9, “M ath” : 88, “Computer Science” : 92, “Science” : 58},
# {“student id” : 10, “M ath” : 90, “Computer Science” : 95, “Science” : 55},
# {“student id” : 11, “M ath” : 70, “Computer Science” : 65, “Science” : 39},
# {“student id” : 12, “M ath” : 65, “Computer Science” : 60, “Science” : 35},
# {“student id” : 13, “M ath” : 60, “Computer Science” : 55, “Science” : 30},
# {“student id” : 14, “M ath” : 55, “Computer Science” : 57, “Science” : 25},
# {“student id” : 15, “M ath” : 49, “Computer Science” : 54, “Science” : 22},
# {“student id” : 16, “M ath” : 10, “Computer Science” : 30, “Science” : 11},
# {“student id” : 17, “M ath” : 50, “Computer Science” : 40, “Science” : 16},
# {“student id” : 18, “M ath” : 90, “Computer Science” : 45, “Science” : 80},
# {“student id” : 19, “M ath” : 70, “Computer Science” : 50, “Science” : 39},
# {“student id” : 20, “M ath” : 70, “Computer Science” : 80, “Science” : 75}]

students = [
    {"student_id": 1, "Math": 50, "Computer_Science": 60, "Science": 73},
    {"student_id": 2, "Math": 40, "Computer_Science": 50, "Science": 55},
    {"student_id": 3, "Math": 90, "Computer_Science": 70, "Science": 95},
    {"student_id": 4, "Math": 80, "Computer_Science": 62, "Science": 72},
    {"student_id": 5, "Math": 80, "Computer_Science": 90, "Science": 45},
    {"student_id": 6, "Math": 84, "Computer_Science": 90, "Science": 50},
    {"student_id": 7, "Math": 90, "Computer_Science": 95, "Science": 55},
    {"student_id": 8, "Math": 89, "Computer_Science": 93, "Science": 53},
    {"student_id": 9, "Math": 88, "Computer_Science": 92, "Science": 58},
    {"student_id": 10, "Math": 90, "Computer_Science": 95, "Science": 55},
    {"student_id": 11, "Math": 70, "Computer_Science": 65, "Science": 39},
    {"student_id": 12, "Math": 65, "Computer_Science": 60, "Science": 35},
    {"student_id": 13, "Math": 60, "Computer_Science": 55, "Science": 30},
    {"student_id": 14, "Math": 55, "Computer_Science": 57, "Science": 25},
    {"student_id": 15, "Math": 49, "Computer_Science": 54, "Science": 22},
    {"student_id": 16, "Math": 10, "Computer_Science": 30, "Science": 11},
    {"student_id": 17, "Math": 50, "Computer_Science": 40, "Science": 16},
    {"student_id": 18, "Math": 90, "Computer_Science": 45, "Science": 80},
    {"student_id": 19, "Math": 70, "Computer_Science": 50, "Science": 39},
    {"student_id": 20, "Math": 70, "Computer_Science": 80, "Science": 75}
]