/*12. Another way to generate the same information as like previous question is to use a cast rather than a
variable within each printf statement. Find the output generated by these statements that make use of
the operator sizeof.*/

#include<stdio.h>
int main(){
	printf("integer:%ld bytes\n", sizeof(int));
	printf("float:%ld bytes\n", sizeof(float));
	printf("double:%ld bytes\n", sizeof(double));
	printf("character:%ld bytes\n", sizeof(char));
}
