/*11. Suppose that i is an integer variable, x is a floating-point variable, d is a double-precision variable
and c is a character-type variable. Find the output generated by these statements that make use of the
operator sizeof.*/

#include<stdio.h>
int main(){
	int i;
	float x;
	double d;
	char c;
	printf("integer:%ld bytes\n", sizeof i);
	printf("integer:%ld bytes\n", sizeof(i));
	printf("float:%ld bytes\n", sizeof x);
	printf("float:%ld bytes\n", sizeof(x));
	printf("double:%ld bytes\n", sizeof d);
	printf("double:%ld bytes\n", sizeof(d));
	printf("character:%ld bytes\n", sizeof c);
	printf("character:%ld bytes\n", sizeof(c));
	return 0;
}
